name: Feature Request
description: Suggest a new feature or improvement for the Surepetcare Integration.
labels: ["enhancement"]
assignees:
  - FredrikM97
body:
  - type: markdown
    attributes:
      value: |
        **Note:** This form is for feature requests related to the IO/API integration only.
        If your request is about the Home Assistant integration, please open an issue in the [hass-surepetcare repository](https://github.com/FredrikM97/hass-surepetcare) instead.
  - type: textarea
    id: summary
    attributes:
      label: Feature summary
      description: Briefly describe the feature or improvement you are requesting.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and use case
      description: Why do you want this feature? What problem does it solve or what value does it add?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples here.
      placeholder: "Related issues, links, or screenshots."

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      description: "Please confirm the following:"
      options:
        - label: I have searched for existing feature requests and this is not a duplicate.
          required: true
        - label: I have provided sufficient detail to understand and evaluate this request.
          required: true
    validations:
      required: true