repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
        pass_filenames: false
        always_run: true

      - id: ruff-format
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --extra dev --extra cli python -m mypy
        args: [surepcio, surepccli, tests]
        language: system
        pass_filenames: false
        always_run: true