version: "3.9"

services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: surepy-jupyter
    volumes:
      - .:/home/jovyan/work
      - ./.env:/home/jovyan/work/.env
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/work
    working_dir: /home/jovyan/work
    command: /bin/bash -c "chmod +x setup.sh && bash setup.sh && start-notebook.py --NotebookApp.token=''"