name: Bump package version
on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Version bump type. pre_n increment pre-release number, move to release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - pre_n
          - pre_l
jobs:
  build:
    permissions:
        id-token: write
        pull-requests: read
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4      
        with:
          fetch-depth: 0     
      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        with:
          args: -vv ${{ inputs.bump-type }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"