name: Publish Python distribution to PyPI and TestPyPI

on:
  push:
    branches:
      - main

jobs:
  check-tag-on-main:
    name: Check for v* tag on main commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for v* tag on HEAD
        id: check_tag
        run: |
          TAG=$(git tag --points-at HEAD | grep '^v' || true)
          if [ -z "$TAG" ]; then
            echo "No v* tag found on this commit. Skipping deployment."
            echo "deploy=false" >> $GITHUB_OUTPUT
          else
            echo "Found tag: $TAG"
            echo "deploy=true" >> $GITHUB_OUTPUT
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi
    outputs:
      deploy: ${{ steps.check_tag.outputs.deploy }}
      tag: ${{ steps.check_tag.outputs.tag }}

  build:
    name: Build distribution
    needs: check-tag-on-main
    if: needs.check-tag-on-main.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ needs.check-tag-on-main.outputs.tag }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/py-surepetcare
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/