name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  verify-version:
    name: Verify tag matches pyproject.toml version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install bump-my-version
        run: pip install bump-my-version
      - name: Check tag and file version
        id: version_check
        run: |
          TAG_VERSION="${{ github.event.release.tag_name#v }}"
          FILE_VERSION=$(bump-my-version show current_version)
          echo "Tag version: $TAG_VERSION"
          echo "pyproject.toml version: $FILE_VERSION"
          if [ "$TAG_VERSION" != "$FILE_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) does not match pyproject.toml version ($FILE_VERSION)."
            exit 1
          fi

  build:
    name: Build distribution
    needs: verify-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    if: startsWith(github.event.release.tag_name, 'v')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/py-surepetcare
    permissions:
      id-token: write 

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1