name: Release Drafter

on:
  push: {branches: [master, main, dev]}
  pull_request: {branches: [master, main, dev]}
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}
