name: Release Drafter

on:
  push:
    branches:
<<<<<<< Updated upstream
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]
=======
      - dev
>>>>>>> Stashed changes

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}

  publish_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}