name: Release Drafter

on:
  push: {branches: [master, main, dev]}
  pull_request: {branches: [master, main, dev]}
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env: {GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"}
